### ISSUE TITLE
Missing semi-colon in QR text

### ISSUE THREAD

**Issue by dolmen** [zdgeier/wifi-code#2]
https://github.com/zdgeier/wifi-code/blob/dafe07c33d83cd19a96a0701f78678a37a06aeb4/index.html#L177
There should be double semi-colon at the end.

Pseudo-specification: https://github.com/zxing/zxing/wiki/Barcode-Contents#wi-fi-network-config-android-ios-11

**Comment by zdgeier** [comment]
thanks! fixed
